import type { Item } from "@prisma/client";
import { useState } from "react";
import { type NextPage } from "next";
import Head from "next/head";
import ItemModal from "../components/ItemModal";
import { api } from "../utils/api";

const Home: NextPage = () => {
  const [items, setItems] = useState<Item[]>([]);
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);

  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>T3 Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isModalOpen && (
        <ItemModal setIsModalOpen={setIsModalOpen} setItems={setItems} />
      )}

      <main className="max mx-auto my-10 max-w-2xl">
        <div className="flex justify-between">
          <h2 className="text-xl font-semibold">My Shopping List</h2>
          <button
            type="button"
            onClick={() => setIsModalOpen(true)}
            className="rounded bg-violet-500 p-2 text-white"
          >
            Add to Shopping Cart
          </button>
        </div>
        <ul>
          {items.map((item) => (
            <li key={item.id} className="flex items-center justify-between">
              <span>{item.name}</span>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
