import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>T3 Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max mx-auto my-10 max-w-2xl">
        <div className="flex justify-between">
          <h2 className="text-xl font-semibold">My Shopping List</h2>
          <button
            type="button"
            className="rounded bg-violet-500 p-2 text-white"
          >
            Add to Shopping Cart
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
